spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/currency_service?currentSchema=currency_service
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect