spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/currency_exchange?currentSchema=currency_exchange
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect